OVERWRITE = False

GENE_TO_PEEK = (
    'ABCG2',
    'BMI1',
    'CD34',
    'CD44',
    'CTNNB1',
    'EPAS1',
    'EZH2',
    'HIF1A',
    'KDM5B',
    'KLF4',
    'LGR5',
    'MYC',
    'NANOG',
    'NES',
    'NOTCH1',
    'POU5F1',
    'PROM1',
    'SOX2',
    'TWIST1',
    'ZFP42',
    'ZSCAN4',
)

GENE_SET_TO_PEEK = (
    'ADDYA_ERYTHROID_DIFFERENTIATION_BY_HEMIN',
    'BENPORATH_ES_CORE_NINE',
    'BENPORATH_ES_WITH_H3K27ME3',
    'BIOCARTA_WNT_PATHWAY',
    'Cancer Stem Cell',
    'E2F3_UP.V1_UP',
    'ESC_V6.5_UP_EARLY.V1_UP',
    'ESC_V6.5_UP_LATE.V1_UP',
    'GAL_LEUKEMIC_STEM_CELL_UP',
    'GOTZMANN_EPITHELIAL_TO_MESENCHYMAL_TRANSITION_UP',
    'HALLMARK_APOPTOSIS',
    'HALLMARK_E2F_TARGETS',
    'HALLMARK_FATTY_ACID_METABOLISM',
    'HALLMARK_G2M_CHECKPOINT',
    'HALLMARK_HYPOXIA',
    'HALLMARK_INFLAMMATORY_RESPONSE',
    'HALLMARK_MITOTIC_SPINDLE',
    'HALLMARK_MYC_TARGETS_V2',
    'HALLMARK_NOTCH_SIGNALING',
    'HALLMARK_OXIDATIVE_PHOSPHORYLATION',
    'HALLMARK_TGF_BETA_SIGNALING',
    'HALLMARK_UV_RESPONSE_UP',
    'HALLMARK_WNT_BETA_CATENIN_SIGNALING',
    'HOEBEKE_LYMPHOID_STEM_CELL_UP',
    'IVANOVA_HEMATOPOIESIS_STEM_CELL_AND_PROGENITOR',
    'IVANOVA_HEMATOPOIESIS_STEM_CELL_LONG_TERM',
    'MA_MYELOID_DIFFERENTIATION_UP',
    'MIKKELSEN_IPS_LCP_WITH_H3K4ME3',
    'MIKKELSEN_IPS_WITH_HCP_H3K27ME3',
    'NOTCH_DN.V1_UP',
    'PARK_OSTEOBLAST_DIFFERENTIATION_BY_PHENYLAMIL_UP',
    'PRC2_EZH2_UP.V1_UP',
    'RHODES_UNDIFFERENTIATED_CANCER',
    'RICKMAN_TUMOR_DIFFERENTIATED_WELL_VS_POORLY_UP',
    'RIZ_ERYTHROID_DIFFERENTIATION_HBZ',
    'RODRIGUES_THYROID_CARCINOMA_POORLY_DIFFERENTIATED_DN',
    'RODRIGUES_THYROID_CARCINOMA_POORLY_DIFFERENTIATED_UP',
    'ZHAN_EARLY_DIFFERENTIATION_GENES_DN',
)

GENE_SET_KEYWORD_TO_PEEK = ()

N_JOB = 1

EXTREME_FEATURE_THRESHOLD = 24

N_SAMPLING = 100

N_PERMUTATION = 100

PLOT_FEATURES_STD_MAX = 2.4
