GENES_TO_PEEK = (
    'SOX2',
    'POU5F1',
    'MYC',
    'KLF4',
    'NANOG',
    'ABCG2',
    'LGR4',
    'CD34',
    'CD44',
    'ZSCAN4',
    'BMI1',
    'HIF1A',
    'EZH2',
    'NES',
    'TWIST1',
    'EPAS1',
    'PROM2',
    'ZFP42',
    'NOTCH1',
    'KDM5B',
    'ALDH1A1',
)

# GENE_SETS_TO_PEEK = ('stem', )

# GENE_SET_KEYWORDS_TO_PEEK = (
#     '_stem_',
#     ' stem ',
# )

GENE_SETS_TO_PEEK = (
    'ADDYA_ERYTHROID_DIFFERENTIATION_BY_HEMIN',
    'BOSCO_EPITHELIAL_DIFFERENTIATION_MODULE',
    'GOBERT_OLIGODENDROCYTE_DIFFERENTIATION_DN',
    'GOBERT_OLIGODENDROCYTE_DIFFERENTIATION_UP',
    'LEE_DIFFERENTIATING_T_LYMPHOCYTE',
    'LE_NEURONAL_DIFFERENTIATION_DN',
    'LE_NEURONAL_DIFFERENTIATION_UP',
    'MATSUDA_NATURAL_KILLER_DIFFERENTIATION',
    'MA_MYELOID_DIFFERENTIATION_UP',
    'MIKKELSEN_DEDIFFERENTIATED_STATE_DN',
    'MIKKELSEN_DEDIFFERENTIATED_STATE_UP',
    'NAKAMURA_LUNG_CANCER_DIFFERENTIATION_MARKERS',
    'PARK_OSTEOBLAST_DIFFERENTIATION_BY_PHENYLAMIL_DN',
    'PARK_OSTEOBLAST_DIFFERENTIATION_BY_PHENYLAMIL_UP',
    'RICKMAN_TUMOR_DIFFERENTIATED_MODERATELY_VS_POORLY_DN',
    'RICKMAN_TUMOR_DIFFERENTIATED_MODERATELY_VS_POORLY_UP',
    'RICKMAN_TUMOR_DIFFERENTIATED_WELL_VS_POORLY_DN',
    'RICKMAN_TUMOR_DIFFERENTIATED_WELL_VS_POORLY_UP',
    'RIZ_ERYTHROID_DIFFERENTIATION_6HR',
    'RIZ_ERYTHROID_DIFFERENTIATION_HBZ',
    'RODRIGUES_THYROID_CARCINOMA_POORLY_DIFFERENTIATED_DN',
    'RODRIGUES_THYROID_CARCINOMA_POORLY_DIFFERENTIATED_UP',
    'URS_ADIPOCYTE_DIFFERENTIATION_UP',
    'ZHAN_EARLY_DIFFERENTIATION_GENES_DN',
    'ZHAN_EARLY_DIFFERENTIATION_GENES_UP',
    'ZHAN_V1_LATE_DIFFERENTIATION_GENES_DN',
    'ZHAN_V1_LATE_DIFFERENTIATION_GENES_UP',
    'ZHAN_VARIABLE_EARLY_DIFFERENTIATION_GENES_UP',
)

GENE_SET_KEYWORDS_TO_PEEK = ()

N_JOB = 16

EXTREME_FEATURE_THRESHOLD = 80

N_SAMPLING = 1000

N_PERMUTATION = 1000
